GET http://localhost:3000/foto

###

GET http://localhost:3000/test/index?name=mapachon

###

GET http://localhost:3000/test/mapache?name=mapachon


###

GET http://localhost:3000/test/mapache/all




